import type { Language, Occurrence, ScheduleEntry } from '../domain/models.ts'
import { addDays, mondayOf, todayInRiga } from '../domain/dates.ts'
import type { Translations } from '../i18n/translations.ts'
import { lessonTypeLabel } from '../i18n/translations.ts'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin } from './icons.tsx'

interface Props { occurrences: Occurrence[]; unfilteredOccurrences: Occurrence[]; uncertain: ScheduleEntry[]; selectedDate: string; language: Language; t: Translations; view: 'agenda' | 'week'; onDate: (date: string) => void; onView: (view: 'agenda' | 'week') => void; onOccurrence: (occurrence: Occurrence) => void }

function DateHeading({ date, language }: { date: string; language: Language }) {
  const epoch = Date.parse(`${date}T12:00:00Z`)
  return <><span className="block text-xs font-semibold uppercase tracking-wider text-base-content/55">{new Intl.DateTimeFormat(language, { weekday: 'long', timeZone: 'UTC' }).format(epoch)}</span><span className="text-lg font-bold">{new Intl.DateTimeFormat(language, { day: 'numeric', month: 'long', timeZone: 'UTC' }).format(epoch)}</span></>
}

function EventCard({ occurrence, language, onClick }: { occurrence: Occurrence; language: Language; onClick: () => void }) {
  const hue = Number.parseInt(occurrence.entry.courseId.slice(-4), 36) % 360
  return <button type="button" onClick={onClick} style={{ '--course-accent': `hsl(${hue} 62% 48%)` } as React.CSSProperties} className="event-card w-full rounded-xl border border-base-300 bg-base-100 p-3 text-left shadow-sm transition-transform hover:-translate-y-px focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary motion-reduce:transition-none">
    <div className="flex gap-3"><div className="w-12 shrink-0"><strong className="block text-base leading-none">{occurrence.startTime}</strong><span className="mt-1 block text-xs text-base-content/55">{occurrence.endTime}</span></div><div className="min-w-0 grow"><div className="flex flex-wrap items-center gap-1.5"><span className="font-mono text-[11px] font-bold text-primary">{occurrence.entry.courseCode}</span><span className="badge badge-ghost badge-sm">{lessonTypeLabel(occurrence.entry.lessonType, language, occurrence.entry.lessonTypeRaw)}</span></div><h3 className="mt-1 font-semibold leading-snug">{occurrence.entry.courseTitle}</h3>{occurrence.entry.location && <p className="mt-2 flex items-start gap-1.5 text-sm text-base-content/70"><MapPin size={15} className="mt-0.5 shrink-0"/><span>{occurrence.entry.location.room || occurrence.entry.location.raw}</span></p>}{occurrence.entry.groupNotes.length > 0 && <p className="mt-1 text-xs font-medium text-secondary">{occurrence.entry.groupNotes.join(' · ')}</p>}</div></div>
  </button>
}

function WeekEventCard({ occurrence, language, onClick }: { occurrence: Occurrence; language: Language; onClick: () => void }) {
  const hue = Number.parseInt(occurrence.entry.courseId.slice(-4), 36) % 360
  return <button type="button" onClick={onClick} style={{ '--course-accent': `hsl(${hue} 62% 48%)` } as React.CSSProperties} className="event-card w-full min-w-0 overflow-hidden rounded-xl border border-base-300 bg-base-100 p-3 text-left shadow-sm transition-transform hover:-translate-y-px focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary motion-reduce:transition-none">
    <div className="flex min-w-0 items-baseline justify-between gap-2"><strong className="text-sm leading-none">{occurrence.startTime}</strong><span className="min-w-0 truncate font-mono text-[10px] font-bold text-primary">{occurrence.entry.courseCode}</span></div>
    <span className="mt-2 inline-flex max-w-full rounded-full bg-base-200 px-2 py-1 text-[10px] font-medium leading-tight text-base-content/75">{lessonTypeLabel(occurrence.entry.lessonType, language, occurrence.entry.lessonTypeRaw)}</span>
    <h3 className="mt-2 line-clamp-3 break-words text-sm font-bold leading-snug [overflow-wrap:anywhere]">{occurrence.entry.courseTitle}</h3>
    {occurrence.entry.location && <p className="mt-2 flex min-w-0 items-center gap-1.5 text-xs text-base-content/65"><MapPin size={13} className="shrink-0"/><span className="min-w-0 truncate">{occurrence.entry.location.room || occurrence.entry.location.raw}</span></p>}
    {occurrence.entry.groupNotes.length > 0 && <p className="mt-1 truncate text-[10px] font-semibold text-secondary" title={occurrence.entry.groupNotes.join(' · ')}>{occurrence.entry.groupNotes.join(' · ')}</p>}
  </button>
}

export function ScheduleView({ occurrences, unfilteredOccurrences, uncertain, selectedDate, language, t, view, onDate, onView, onOccurrence }: Props) {
  const weekStart = mondayOf(selectedDate)
  const dates = Array.from({ length: 7 }, (_, index) => addDays(weekStart, index))
  const dateLabel = (date: string) => new Intl.DateTimeFormat(language, {
    dateStyle: 'full', timeZone: 'UTC',
  }).format(Date.parse(`${date}T12:00:00Z`))
  return <>
    <div className="mt-5 flex flex-wrap items-center justify-center gap-3 sm:justify-between"><div className="join rounded-box border border-base-300 bg-base-100 p-1 shadow-md"><button className="btn btn-ghost btn-square join-item min-h-11" aria-label={t.previousWeek} onClick={() => onDate(addDays(selectedDate, -7))}><ChevronLeft/></button><button className="btn btn-ghost join-item min-h-11 min-w-24 border-x border-base-300 px-4 font-bold" onClick={() => onDate(todayInRiga())}>{t.today}</button><button className="btn btn-ghost btn-square join-item min-h-11" aria-label={t.nextWeek} onClick={() => onDate(addDays(selectedDate, 7))}><ChevronRight/></button></div><div className="join hidden rounded-box border border-base-300 bg-base-100 p-1 shadow-md lg:inline-flex"><button className={`btn join-item min-h-11 min-w-24 font-bold ${view === 'agenda' ? 'btn-primary' : 'btn-ghost'}`} aria-pressed={view === 'agenda'} onClick={() => onView('agenda')}>{t.agenda}</button><button className={`btn join-item min-h-11 min-w-24 font-bold ${view === 'week' ? 'btn-primary' : 'btn-ghost'}`} aria-pressed={view === 'week'} onClick={() => onView('week')}>{t.week}</button></div></div>
    <div className="mt-3 grid grid-cols-7 gap-1 rounded-2xl bg-base-200 p-1.5">{dates.map((date, index) => { const epoch = Date.parse(`${date}T12:00:00Z`); const active = date === selectedDate; const count = occurrences.filter((item) => item.date === date).length; const hasPublishedClasses = unfilteredOccurrences.some((item) => item.date === date); const quietWeekend = index >= 5 && !hasPublishedClasses; return <button key={date} className={`min-h-14 rounded-xl px-1 text-center ${active ? 'bg-primary text-primary-content shadow-sm' : quietWeekend ? 'bg-secondary/5 hover:bg-secondary/10' : 'hover:bg-base-100'}`} onClick={() => onDate(date)} aria-label={dateLabel(date)} aria-current={active ? 'date' : undefined}><span className="block text-[10px] font-bold uppercase">{new Intl.DateTimeFormat(language, { weekday: 'narrow', timeZone: 'UTC' }).format(epoch)}</span><span className="block text-base font-semibold">{Number(date.slice(-2))}</span><span className={`mx-auto mt-0.5 block size-1 rounded-full ${count ? active ? 'bg-primary-content' : 'bg-primary' : 'bg-transparent'}`}/></button> })}</div>
    <section className={`${view === 'week' ? 'lg:hidden' : ''} mt-6 space-y-4`}>{dates.map((date, index) => { const dayOccurrences = occurrences.filter((item) => item.date === date); const hasPublishedClasses = unfilteredOccurrences.some((item) => item.date === date); const active = date === selectedDate; const quietWeekend = index >= 5 && !hasPublishedClasses; return <article key={date} data-date={date} data-weekend={index >= 5 ? 'true' : undefined} className={`scroll-mt-36 rounded-2xl border p-3 sm:p-4 ${active ? 'border-primary/50 bg-primary/5 shadow-sm' : quietWeekend ? 'border-secondary/10 bg-secondary/5' : 'border-transparent'}`}><header className={`mb-3 border-b px-1 pb-2 ${active ? 'border-primary/25' : quietWeekend ? 'border-secondary/15' : 'border-base-300'}`}><DateHeading date={date} language={language}/></header><div className="space-y-2">{dayOccurrences.map((item) => <EventCard key={item.id} occurrence={item} language={language} onClick={() => onOccurrence(item)}/>)}</div>{!dayOccurrences.length && <div className={`rounded-box border border-dashed px-5 py-6 text-center ${quietWeekend ? 'border-secondary/15 bg-base-100/35' : 'border-base-300 bg-base-100'}`}><CalendarDays className="mx-auto text-base-content/30"/><p className="mt-2 text-sm font-medium text-base-content/60">{hasPublishedClasses ? t.filteredEmpty : t.noClasses}</p></div>}</article> })}</section>
    {view === 'week' && <section className="mt-6 hidden grid-cols-7 gap-3 lg:grid">{dates.map((date, index) => { const dayOccurrences = occurrences.filter((item) => item.date === date); const hasPublishedClasses = unfilteredOccurrences.some((item) => item.date === date); const quietWeekend = index >= 5 && !hasPublishedClasses; return <div key={date} data-date={date} data-weekend={index >= 5 ? 'true' : undefined} className={`min-w-0 rounded-xl p-2 ${quietWeekend ? 'bg-secondary/5' : ''}`}><header className={`mb-3 border-b px-1 pb-2 text-center ${quietWeekend ? 'border-secondary/15' : 'border-base-300'}`}><DateHeading date={date} language={language}/></header><div className="space-y-2">{dayOccurrences.map((item) => <WeekEventCard key={item.id} occurrence={item} language={language} onClick={() => onOccurrence(item)}/>)}</div>{!dayOccurrences.length && <p className="rounded-lg border border-dashed border-base-300/60 px-2 py-4 text-center text-xs text-base-content/45">{hasPublishedClasses ? t.filteredEmpty : t.noClasses}</p>}</div> })}</section>}
    {uncertain.length > 0 && <details className="collapse-arrow collapse mt-6 border border-warning/40 bg-warning/10"><summary className="collapse-title min-h-12 py-3 font-semibold">{t.datesChecking} <span className="badge badge-warning badge-sm ml-1">{uncertain.length}</span></summary><div className="collapse-content text-sm"><p className="mb-3 text-base-content/70">{t.datesCheckingHelp}</p><div className="space-y-2">{uncertain.map((entry) => <a key={entry.id} className="flex items-center gap-3 rounded-lg bg-base-100 p-3 hover:underline" href={entry.sourceUrl} target="_blank" rel="noreferrer"><Clock3 size={16}/><span><strong>{entry.courseCode}</strong> {entry.courseTitle}<span className="block text-xs text-base-content/60">{entry.startTime} · {entry.recurrence.raw}</span></span></a>)}</div></div></details>}
  </>
}
